import css from "./Reviews.module.css";

const Reviews = () => {
  return (
    <ul className={css.list}>
      <li className={css.item}>
        <div className={css.author}>
          Author: NeoBrowser
        </div>
        <p>Brooking no argument, history should quickly regard Peter Jackson’s The Fellowship Of The Ring as the first instalment of the best fantasy epic in motion picture history. This statement is worthy of investigation for several reasons. Fellowship is indeed merely an opening salvo, and even after three hours in the dark you will likely exit the cinema ravenous with anticipation for the further two parts of the trilogy. Fellowship is also unabashedly rooted in the fantasy genre. Not to be confused with the techno-cool of good science fiction, nor even the cutesy charm of family fare like Harry Potter, the territory of Tolkien is clearly marked by goo and goblins and gobbledegook. Persons with an aversion to lines such as, “To the bridge of Khazad-dûm!” are as well to stay within the Shire-like comforts of home (their loss). With those caveats in place, it bears repeating: fantasy does not come finer. There are electrifying moments — notably the computer-assisted swooping camera through Isengard as it transforms into a factory for evil — when Jackson’s flight of fancy approaches the sublime as the romantic poets would understand it: inspiring awe. Leaving aside the thorny issue of Tolkien die-hards and their inevitable gripes — “What no Tom Bombadil?” — Jackson’s screenplay (written in collaboration with Fran Walsh and Phillipa Boyens) is both bolder and more judicious than Steven Kloves’ surprisingly timid retread of Harry Potter. In particular, rescuing the romance of Arwen and Aragorn from the footnotes and the elevation of Saruman to all-action bad guy actually has a corrective influence on Tolkien’s often oblique and female-sparse source material. There are problems, though. The three-hour running time is high on incident and low on discernible form. After successive detours to Elf habitats Rivendell (the watery home of Elrond) and Lothlórien (the forest home of the Lady Galadriel), the uninitiated might well ask why these crazy Elf kids can’t just live together and spare us all this attenuated dramatic structure. More importantly, the action clearly climaxes in the desperate flight from the Mines Of Moria, where the largely seamless SFX is showcased in the best possible light — total darkness — but the narrative demands a different, downbeat ending. Indeed, but for some fine emotional playing from Bean, Mortensen, Astin and Wood, the final fight might feel like a particularly brutal game of paintball in Bluebell Wood. But then, the real battles are yet to come... Verdict - Putting formula blockbusters to shame, Fellowship is impeccably cast and constructed with both care and passion: this is a labour of love that never feels laboured. Emotional range and character depth ultimately take us beyond genre limitations, and it deserves to play as wide as a certain Mr. Potter. 5/5 - Colin Kennedy, Empire Magazine</p>
      </li>
      <li className={css.item}>
        <div className={css.author}>
          Author: gdeveloper
        </div>
        <p>An epic movie if I ever saw one. Captivating and just plain fun to watch. This movie is, indeed, art.</p>
      </li>
      <li className={css.item}>
        <div className={css.author}>
          Author: Wuchak
        </div>
        <p>Tolkien’s adventure/fantasy LOOKS and SOUNDS fabulous, but is not without flaws. RELEASED 2001 and directed by Peter Jackson, “The Lord of the Rings: The Fellowship of the Ring” adapts the first part of JRR Tolkien’s popular fantasy trilogy about adventures on Middle-Earth. The story starts in the homeland of the Hobbits (innocent, diminutive humanoids) where Frodo (Elijah Wood) is instructed by the noble wizard Gandalf (Ian McKellen) to quickly leave the Shire with the powerful One Ring in his possession. Gandalf and Frodo are later accompanied by seven others, the titular ‘Fellowship of the Ring,’ to take the ring to the only place it can be destroyed, the fires of Mount Doom in Mordor. The rest of the main cast include Sean Astin (Sam), Viggo Mortensen (Aragorn), Sean Bean (Boromir), Christopher Lee (Saruman), Orlando Bloom (Legolas), John Rhys-Davies (Gimli) and Hugo Weaving (Elrond). This three-hour fantasy features a diverse cast of colorful characters, quaint beings and settings, moments of genuine wonder, dark ee-vil creatures, high adventure, thrilling brutal action, a superb score, magnificent locations (forests, mountains, rivers, etc.), and wondrous CGI sets. The film LOOKS and SOUNDS so great that it’d be sinful to give it a lower rating. There are problems, however, at least for those who aren’t uber-fans of Tolkien. For one, the opening is hindered by prologue that is overlong and convoluted, not to mention unnecessary. The bulk of it could’ve been conveyed later via flashback, which they do a little bit anyway. Secondly, the story takes forever to build any drive. Thirdly, except for maybe Frodo and Gandalf, the characters are shallow and I didn’t care much what happened to them. Fourthly, main protagonists getting seriously wounded and everyone else expressing their melodramatic concern gets redundant. Fifthly, there are only two females in the main cast (Liv Tyler as Arwen, a half-Elf princess, and Cate Blanchett as Galadriel, a royal Elf); unfortunately, their parts aren’t much more than glorified cameos. “Mythica: A Quest for Heroes” (2014) cost LESS THAN $100,000 to make, which is a mere fraction of the $93 million it cost to make this blockbuster and the filmmakers knew enough to include a couple of prominent babes as key protagonists in the story. Despite these negatives, “The Fellowship of the Ring” is the best of the trilogy and is a must for fantasy/adventure aficionados, especially Tolkien fans. THE MOVIE RUNS 2 hours 58 minutes and was shot in New Zealand. GRADE: B/B- (6.5/10)</p>
      </li>
    </ul>
  )
};

export default Reviews;